name: know_my_city
description: "Proyecto para promover el turismo en la capital"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  go_router: ^14.2.7 # Enrutador de pantallas
  dartz: ^0.10.1 # Either, una nueva forma de manejar respuesta
  get_it: ^7.7.0 # Localizador de instancias creadas
  flutter_bloc: ^8.1.6 # Libreria para aplicar el patron bloc
  freezed: ^2.5.7 # Autogenerador de codigo usado, para crear propiedades elementales que debe tener una clase
  build_runner: ^2.4.12 # Motor de los autogeneradores de codigos, como freezed y injection
  freezed_annotation: ^2.4.4 # Anotaciones para utilizar el modulo de freezed
  injectable: ^2.4.4 # Paquete de anotaciones para utilizar el patron de inyeccion de dependencias
  firebase_auth: ^5.3.0
  bloc: ^8.1.4
  injectable_generator: ^2.6.2
  cloud_firestore: ^5.4.2
  google_maps_flutter: ^2.9.0
  dio: ^4.0.0
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: AlcaldiaFonts
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf

  assets:
    - lib/presentation/core/map_style.json
    - assets/data4iflogo.png
    - assets/shrek.png
    - assets/tranvia.png
    - assets/obelisco.png